### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 0)

### ISSUE THREAD

**Issue by Liu98Fan** [umautobots/vod-converter#19]
Traceback (most recent call last):
  File "vod_converter/main.py", line 92, in <module>
    filter_images_without_labels=args.filter_images_without_labels))
  File "vod_converter/main.py", line 40, in main
    filter_images_without_labels=filter_images_without_labels)
  File "/media/liufan/689097F39097C64A/ubuntu16.04/dataConverter/vod-converter/vod_converter/converter.py", line 133, in convert
    image_detections = ingestor.ingest(from_path)
  File "/media/liufan/689097F39097C64A/ubuntu16.04/dataConverter/vod-converter/vod_converter/kitti.py", line 60, in ingest
    return [self._get_image_detection(path, image_name, image_ext=image_ext) for image_name in image_ids]
  File "/media/liufan/689097F39097C64A/ubuntu16.04/dataConverter/vod-converter/vod_converter/kitti.py", line 60, in <listcomp>
    return [self._get_image_detection(path, image_name, image_ext=image_ext) for image_name in image_ids]
  File "/media/liufan/689097F39097C64A/ubuntu16.04/dataConverter/vod-converter/vod_converter/kitti.py", line 75, in _get_image_detection
    detections = self._get_detections(detections_fpath)
  File "/media/liufan/689097F39097C64A/ubuntu16.04/dataConverter/vod-converter/vod_converter/kitti.py", line 95, in _get_detections
    x1, y1, x2, y2 = map(float, row[4:8])

**Comment by Liu98Fan** [comment]
Sorry,it's my fault.I put the word 'train' into the file 'train.txt',program running at csv.reader also read the train.txt and naturally can't found x1x2y1y2 to the map
