### ISSUE TITLE
Converters not working

### ISSUE THREAD

**Issue by benn94** [umautobots/vod-converter#6]
I would like to convert udacity to voc. I wonder whether the converter I am using  is right or not because it keep giving me error

## First i tried this `main.py`

`~/Documents/vod-converter$ python3.6 vod_converter/main.py --from udacity --from-path datasets/mydata-udacity/ --to voc --to-path datasets/mydata-voc/
`
## output is 

```
Traceback (most recent call last):
  File "vod_converter/main.py", line 12, in <module>
    import kitti
  File "/home/borinyun/Documents/vod-converter/vod_converter/kitti.py", line 35, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "vod_converter/main.py", line 12, in <module>
    import kitti
  File "/home/borinyun/Documents/vod-converter/vod_converter/kitti.py", line 35, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging'

```

## Then I tried this `udacity.py`

`~/Documents/vod-converter$ python3.6 vod_converter/udacity.py --from udacity --from-path datasets/mydata-udacity/ --to voc --to-path datasets/mydata-voc/`

## output

```
Traceback (most recent call last):
  File "vod_converter/udacity.py", line 10, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "vod_converter/udacity.py", line 10, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: cannot import name '_imaging'

```

**Comment by krosaen** [comment]
could you try installing `pillow`? e.g 

`$ sudo python3.6 -m pip install pillow`

**Comment by benn94** [comment]
@krosaen it's still not working.

**Comment by krosaen** [comment]
python3.6 is required for [literal string interpolation](https://www.python.org/dev/peps/pep-0498/)

**Comment by benn94** [comment]
@krosaen now it works. I think it is the dependency problem on my machine. I will close this issue now.
